### PR TITLE
Fixed subfolders not unpacked error

### PR DESCRIPTION
**Pull request by antoniozh**
Hi, I found out that this method is called twice, but not recursively on it's subfolders. I tested it with a download and my downloads are working now.

### CODE REVIEW

**Comment by antoniozh** [comment]
@dnzbk @phnzb any chance you could review this? Thanks.

**Comment by dnzbk** [comment]
> @dnzbk @phnzb any chance you could review this? Thanks.

Hi, I should have noticed your PR much earlier, I apologize.


I added the launch of tests in pipelines and improved the tests themselves by adding a nested directories to them.
You could try to pull the last changes from main and then the pailine with tests should start automatically allowing us to test your changes.
Aslo you can try running the tests locally with the `python ./tests.py` command but don't forget to privide a [path](https://github.com/nzbgetcom/Extension-ExtendedUnrar/blob/40867169d73a2eb1c382b444422843a72ee8b90f/tests.py#L32) to `unrar`.

Unfortunately I formatted the code using [Black](https://pypi.org/project/black/) formatter and there are conflicts, sorry for that.
We'll integrate the code formatter into the pipeline a bit later.

**Comment by antoniozh** [comment]
Hi, I think I found the issue. I mistakenly thought os.walk does not output nested files, but to me it seems like that in the unrar_recursively method the len(rars) == 0 if clause will just exit the whole function if the first folder has no rar files? Maybe the test case should include that or instead of returning, it should skip the for loop iteration with `continue` instead of `return`.

**Comment by dnzbk** [comment]
> Hi, I think I found the issue. I mistakenly thought os.walk does not output nested files, but to me it seems like that in the unrar_recursively method the len(rars) == 0 if clause will just exit the whole function if the first folder has no rar files? Maybe the test case should include that or instead of returning, it should skip the for loop iteration with `continue` instead of `return`.

If you see that my test is not good enough and does not cover all possible cases, feel free to improve it. 
I would only welcome that.

**Pull request closed without merging**
